import { Metadata } from "next";
import "./globals.css";
import Navbar from "@components/Navbar";

export const metadata: Metadata = {
  title: "Dheeraj Kushwah | Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-ibm">
        <div className="flex h-screen">
          <Navbar />
          <div className="ml-[48px] lg:ml-[280px] h-screen overflow-auto w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
